// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.siliph.siliph.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SiliphBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Metadata for a document addressed by a content URI.
 *
 * [sizeBytes] is -1 when unknown; [lastModifiedMillis] is 0 when unknown.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FileMeta (
  val uri: String,
  val displayName: String,
  val mimeType: String? = null,
  val sizeBytes: Long,
  val lastModifiedMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FileMeta {
      val uri = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val mimeType = pigeonVar_list[2] as String?
      val sizeBytes = pigeonVar_list[3] as Long
      val lastModifiedMillis = pigeonVar_list[4] as Long
      return FileMeta(uri, displayName, mimeType, sizeBytes, lastModifiedMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      displayName,
      mimeType,
      sizeBytes,
      lastModifiedMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FileMeta
    return SiliphBridgePigeonUtils.deepEquals(this.uri, other.uri) && SiliphBridgePigeonUtils.deepEquals(this.displayName, other.displayName) && SiliphBridgePigeonUtils.deepEquals(this.mimeType, other.mimeType) && SiliphBridgePigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && SiliphBridgePigeonUtils.deepEquals(this.lastModifiedMillis, other.lastModifiedMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.uri)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.displayName)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.mimeType)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.lastModifiedMillis)
    return result
  }
  override fun toString(): String {
    return "FileMeta(uri=$uri, displayName=$displayName, mimeType=$mimeType, sizeBytes=$sizeBytes, lastModifiedMillis=$lastModifiedMillis)"
  }
}

/**
 * Lightweight PDF inspection result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PdfInfo (
  val uri: String,
  val pageCount: Long,
  val encrypted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PdfInfo {
      val uri = pigeonVar_list[0] as String
      val pageCount = pigeonVar_list[1] as Long
      val encrypted = pigeonVar_list[2] as Boolean
      return PdfInfo(uri, pageCount, encrypted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      pageCount,
      encrypted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PdfInfo
    return SiliphBridgePigeonUtils.deepEquals(this.uri, other.uri) && SiliphBridgePigeonUtils.deepEquals(this.pageCount, other.pageCount) && SiliphBridgePigeonUtils.deepEquals(this.encrypted, other.encrypted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.uri)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.pageCount)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.encrypted)
    return result
  }
  override fun toString(): String {
    return "PdfInfo(uri=$uri, pageCount=$pageCount, encrypted=$encrypted)"
  }
}

/**
 * Editable document-information fields (section 15).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PdfMetadata (
  val title: String? = null,
  val author: String? = null,
  val subject: String? = null,
  val keywords: String? = null,
  val creator: String? = null,
  val producer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PdfMetadata {
      val title = pigeonVar_list[0] as String?
      val author = pigeonVar_list[1] as String?
      val subject = pigeonVar_list[2] as String?
      val keywords = pigeonVar_list[3] as String?
      val creator = pigeonVar_list[4] as String?
      val producer = pigeonVar_list[5] as String?
      return PdfMetadata(title, author, subject, keywords, creator, producer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      author,
      subject,
      keywords,
      creator,
      producer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PdfMetadata
    return SiliphBridgePigeonUtils.deepEquals(this.title, other.title) && SiliphBridgePigeonUtils.deepEquals(this.author, other.author) && SiliphBridgePigeonUtils.deepEquals(this.subject, other.subject) && SiliphBridgePigeonUtils.deepEquals(this.keywords, other.keywords) && SiliphBridgePigeonUtils.deepEquals(this.creator, other.creator) && SiliphBridgePigeonUtils.deepEquals(this.producer, other.producer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.title)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.author)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.subject)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.keywords)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.creator)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.producer)
    return result
  }
  override fun toString(): String {
    return "PdfMetadata(title=$title, author=$author, subject=$subject, keywords=$keywords, creator=$creator, producer=$producer)"
  }
}

/**
 * One group of byte-identical files discovered by the duplicate finder.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DuplicateGroup (
  val sizeBytes: Long,
  val uris: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DuplicateGroup {
      val sizeBytes = pigeonVar_list[0] as Long
      val uris = pigeonVar_list[1] as List<String>
      return DuplicateGroup(sizeBytes, uris)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sizeBytes,
      uris,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DuplicateGroup
    return SiliphBridgePigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && SiliphBridgePigeonUtils.deepEquals(this.uris, other.uris)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.uris)
    return result
  }
  override fun toString(): String {
    return "DuplicateGroup(sizeBytes=$sizeBytes, uris=$uris)"
  }
}

/**
 * Size breakdown entry reported by the storage analyzer.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageEntry (
  val name: String,
  val uri: String,
  val sizeBytes: Long,
  val fileCount: Long,
  val folder: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageEntry {
      val name = pigeonVar_list[0] as String
      val uri = pigeonVar_list[1] as String
      val sizeBytes = pigeonVar_list[2] as Long
      val fileCount = pigeonVar_list[3] as Long
      val folder = pigeonVar_list[4] as Boolean
      return StorageEntry(name, uri, sizeBytes, fileCount, folder)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      uri,
      sizeBytes,
      fileCount,
      folder,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageEntry
    return SiliphBridgePigeonUtils.deepEquals(this.name, other.name) && SiliphBridgePigeonUtils.deepEquals(this.uri, other.uri) && SiliphBridgePigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && SiliphBridgePigeonUtils.deepEquals(this.fileCount, other.fileCount) && SiliphBridgePigeonUtils.deepEquals(this.folder, other.folder)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.name)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.uri)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.fileCount)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.folder)
    return result
  }
  override fun toString(): String {
    return "StorageEntry(name=$name, uri=$uri, sizeBytes=$sizeBytes, fileCount=$fileCount, folder=$folder)"
  }
}

/**
 * Image inspection result (named to avoid clashing with Flutter's own
 * ImageInfo). [format] is 'jpeg', 'png', 'webp' or 'unknown'.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ImageFacts (
  val width: Long,
  val height: Long,
  val format: String,
  val sizeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageFacts {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val format = pigeonVar_list[2] as String
      val sizeBytes = pigeonVar_list[3] as Long
      return ImageFacts(width, height, format, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      format,
      sizeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageFacts
    return SiliphBridgePigeonUtils.deepEquals(this.width, other.width) && SiliphBridgePigeonUtils.deepEquals(this.height, other.height) && SiliphBridgePigeonUtils.deepEquals(this.format, other.format) && SiliphBridgePigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.width)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.height)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.format)
    result = 31 * result + SiliphBridgePigeonUtils.deepHash(this.sizeBytes)
    return result
  }
  override fun toString(): String {
    return "ImageFacts(width=$width, height=$height, format=$format, sizeBytes=$sizeBytes)"
  }
}
private open class SiliphBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FileMeta.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfMetadata.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DuplicateGroup.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageEntry.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageFacts.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FileMeta -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PdfInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PdfMetadata -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DuplicateGroup -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is StorageEntry -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ImageFacts -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * SAF / Photo Picker file intake and export (sections 60, 180).
 *
 * Picker methods launch a system UI and resolve through [FileResultsApi];
 * they never block the platform thread.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FileAccessApi {
  /**
   * ACTION_OPEN_DOCUMENT with multi-select; result via
   * [FileResultsApi.onOpenResult] (empty list when the user cancels).
   */
  fun requestOpenDocuments(mimeTypes: List<String>)
  /** Android Photo Picker; result via [FileResultsApi.onPickImagesResult]. */
  fun requestPickImages(maxItems: Long)
  /** ACTION_CREATE_DOCUMENT; result via [FileResultsApi.onCreateDocumentResult]. */
  fun requestCreateDocument(mimeType: String, displayName: String)
  /** Metadata for a previously picked/created URI. */
  fun getMetadata(uri: String): FileMeta
  /**
   * Renames the SAF document at [uri] (section 34) and returns its fresh
   * metadata. Throws FlutterError `not_supported` when the provider
   * refuses the rename, `invalid_input` for an unusable name.
   */
  fun renameDocument(uri: String, newDisplayName: String): FileMeta
  /**
   * Deletes the SAF document at [uri] (section 34). Returns true when the
   * provider confirms deletion. Destructive and irreversible.
   */
  fun deleteDocument(uri: String): Boolean
  /**
   * ACTION_OPEN_DOCUMENT_TREE; result via
   * [FileResultsApi.onPickFolderResult] (null when the user cancels).
   */
  fun requestPickFolder()
  /**
   * Copies [uri] into the tree picked via [requestPickFolder] and returns
   * the new document's metadata. Throws `not_supported` when the provider
   * refuses.
   */
  fun copyDocument(uri: String, targetTreeUri: String): FileMeta
  /**
   * Moves [uri] into the target tree. The source parent is resolved with
   * DocumentsContract.findDocumentPath; throws `not_supported` when the
   * provider cannot provide it.
   */
  fun moveDocument(uri: String, targetTreeUri: String): FileMeta
  /** Launches the system share sheet for the document. */
  fun shareDocument(uri: String, mimeType: String)
  /** Releases a persisted URI permission we no longer need. */
  fun releasePersistablePermission(uri: String): Boolean
  /** App-owned cache workspace for intermediate files (section 5 boundary). */
  fun tempDirectory(): String

  companion object {
    /** The codec used by FileAccessApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
    /** Sets up an instance of `FileAccessApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FileAccessApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.requestOpenDocuments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mimeTypesArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.requestOpenDocuments(mimeTypesArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.requestPickImages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxItemsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.requestPickImages(maxItemsArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.requestCreateDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mimeTypeArg = args[0] as String
            val displayNameArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.requestCreateDocument(mimeTypeArg, displayNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.getMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getMetadata(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.renameDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val newDisplayNameArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.renameDocument(uriArg, newDisplayNameArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.deleteDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteDocument(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.requestPickFolder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestPickFolder()
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.copyDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val targetTreeUriArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.copyDocument(uriArg, targetTreeUriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.moveDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val targetTreeUriArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.moveDocument(uriArg, targetTreeUriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.shareDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val mimeTypeArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.shareDocument(uriArg, mimeTypeArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.releasePersistablePermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.releasePersistablePermission(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileAccessApi.tempDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.tempDirectory())
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * PDF operations backed by the native engine (sections 5, 192).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PdfApi {
  /**
   * Page count + encryption flag. Throws FlutterError `invalid_pdf` or
   * `io_error` on failure.
   */
  fun inspect(uri: String): PdfInfo
  /**
   * Starts merging [inputUris] in order into [outputUri] on a worker
   * thread. Progress/completion/cancellation arrive through [TaskEventsApi].
   */
  fun startMerge(inputUris: List<String>, outputUri: String, taskId: String)
  /**
   * Rebuilds [uri] keeping only the zero-based pages in [pageOrder], in
   * that order. Covers extract, delete, reorder, reverse and duplicate.
   */
  fun startRearrangePages(uri: String, pageOrder: List<Long>, outputUri: String, taskId: String)
  /**
   * Adds [rotationDelta] degrees (typically 90/180/270) to the existing
   * rotation of one-based pages [firstPage]..[lastPage] inclusive.
   */
  fun startRotatePages(uri: String, firstPage: Long, lastPage: Long, rotationDelta: Long, outputUri: String, taskId: String)
  /** Reads the document-information dictionary (section 15). */
  fun readMetadata(uri: String): PdfMetadata
  /**
   * Writes [metadata] over the source info dictionary (or strips every
   * field when [removeAll] is true) and saves a copy to [outputUri].
   */
  fun startWriteMetadata(uri: String, metadata: PdfMetadata, removeAll: Boolean, outputUri: String, taskId: String)
  /**
   * Re-encodes [uri] at compression [level] (0 low, 1 medium, 2 high).
   * Honest rasterized compression: pages are rendered, downscaled and
   * rebuilt, so text becomes non-selectable in the output.
   */
  fun startCompress(uri: String, level: Long, outputUri: String, taskId: String)
  /** Builds a new PDF from the picked images, one image per page, in order. */
  fun startImagesToPdf(imageUris: List<String>, outputUri: String, taskId: String)
  /**
   * Renders every page of [uri] at [dpi] and saves one PNG per page into
   * the SAF tree [folderTreeUri]. Created file URIs arrive through
   * [TaskEventsApi.onFilesResult] before [TaskEventsApi.onComplete].
   */
  fun startPdfToImages(uri: String, dpi: Long, folderTreeUri: String, taskId: String)
  /**
   * Overlays [text] on every page. [position]: `diagonal`, `bottom`,
   * `top`.
   */
  fun startWatermark(uri: String, text: String, position: String, outputUri: String, taskId: String)
  /** Encrypts the output with [password] (user + owner). */
  fun startProtect(uri: String, password: String, outputUri: String, taskId: String)
  /**
   * Decrypts [uri] using [password] and saves an unencrypted copy.
   * Throws `invalid_input` for a wrong password.
   */
  fun startUnlock(uri: String, password: String, outputUri: String, taskId: String)
  /** Requests cancellation of a running task. Safe when unknown. */
  fun cancel(taskId: String)

  companion object {
    /** The codec used by PdfApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
    /** Sets up an instance of `PdfApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PdfApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.inspect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.inspect(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startMerge$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputUrisArg = args[0] as List<String>
            val outputUriArg = args[1] as String
            val taskIdArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.startMerge(inputUrisArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startRearrangePages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val pageOrderArg = args[1] as List<Long>
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startRearrangePages(uriArg, pageOrderArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startRotatePages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val firstPageArg = args[1] as Long
            val lastPageArg = args[2] as Long
            val rotationDeltaArg = args[3] as Long
            val outputUriArg = args[4] as String
            val taskIdArg = args[5] as String
            val wrapped: List<Any?> = try {
              api.startRotatePages(uriArg, firstPageArg, lastPageArg, rotationDeltaArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.readMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.readMetadata(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startWriteMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val metadataArg = args[1] as PdfMetadata
            val removeAllArg = args[2] as Boolean
            val outputUriArg = args[3] as String
            val taskIdArg = args[4] as String
            val wrapped: List<Any?> = try {
              api.startWriteMetadata(uriArg, metadataArg, removeAllArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startCompress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val levelArg = args[1] as Long
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startCompress(uriArg, levelArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startImagesToPdf$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageUrisArg = args[0] as List<String>
            val outputUriArg = args[1] as String
            val taskIdArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.startImagesToPdf(imageUrisArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startPdfToImages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val dpiArg = args[1] as Long
            val folderTreeUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startPdfToImages(uriArg, dpiArg, folderTreeUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startWatermark$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val textArg = args[1] as String
            val positionArg = args[2] as String
            val outputUriArg = args[3] as String
            val taskIdArg = args[4] as String
            val wrapped: List<Any?> = try {
              api.startWatermark(uriArg, textArg, positionArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startProtect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val passwordArg = args[1] as String
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startProtect(uriArg, passwordArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.startUnlock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val passwordArg = args[1] as String
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startUnlock(uriArg, passwordArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.PdfApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * File utilities built on platform APIs only (ZIP, QR, folder analysis).
 *
 * Long-running work follows the same request + event contract as [PdfApi];
 * results beyond the negotiated output arrive through [TaskEventsApi].
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FileToolsApi {
  /** Streams the picked files into a ZIP archive at [outputUri]. */
  fun startZipCreate(inputUris: List<String>, outputUri: String, taskId: String)
  /**
   * Extracts [zipUri] into the SAF tree [folderTreeUri]. Created file
   * URIs arrive through [TaskEventsApi.onFilesResult] before
   * [TaskEventsApi.onComplete]. Unsafe entry names (path traversal,
   * absolute paths) are skipped rather than written.
   */
  fun startZipExtract(zipUri: String, folderTreeUri: String, taskId: String)
  /**
   * Hashes every file under [folderTreeUri] and reports groups of two or
   * more byte-identical files through [TaskEventsApi.onDuplicatesResult]
   * before completion.
   */
  fun startFindDuplicates(folderTreeUri: String, taskId: String)
  /**
   * Walks [folderTreeUri] and reports each top-level child's total size
   * through [TaskEventsApi.onStorageResult] before completion.
   */
  fun startAnalyzeStorage(folderTreeUri: String, taskId: String)
  /**
   * Renders [content] as a QR code PNG into [outputUri]. [ecLevel]:
   * 0 low, 1 medium, 2 quartile, 3 high. Synchronous because generation
   * is fast; throws `invalid_input` when the content is empty or too long.
   */
  fun generateQr(content: String, ecLevel: Long, outputUri: String)
  /** Requests cancellation of a running task. Safe when unknown. */
  fun cancel(taskId: String)

  companion object {
    /** The codec used by FileToolsApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
    /** Sets up an instance of `FileToolsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FileToolsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.startZipCreate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputUrisArg = args[0] as List<String>
            val outputUriArg = args[1] as String
            val taskIdArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.startZipCreate(inputUrisArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.startZipExtract$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val zipUriArg = args[0] as String
            val folderTreeUriArg = args[1] as String
            val taskIdArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.startZipExtract(zipUriArg, folderTreeUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.startFindDuplicates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val folderTreeUriArg = args[0] as String
            val taskIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.startFindDuplicates(folderTreeUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.startAnalyzeStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val folderTreeUriArg = args[0] as String
            val taskIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.startAnalyzeStorage(folderTreeUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.generateQr$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentArg = args[0] as String
            val ecLevelArg = args[1] as Long
            val outputUriArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.generateQr(contentArg, ecLevelArg, outputUriArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.FileToolsApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Image tools built on platform BitmapFactory/Bitmap APIs only.
 *
 * Every op re-encodes the image, so EXIF metadata never survives into the
 * output. Progress/completion/cancellation follow the same request + event
 * contract as [PdfApi] and [FileToolsApi].
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ImageToolsApi {
  /**
   * Dimensions + format of the image at [uri]. Throws `invalid_input`
   * when the document is not a decodable image.
   */
  fun inspectImage(uri: String): ImageFacts
  /** Re-encodes [uri] as [format] ('jpeg' or 'webp') at [quality] 1..100. */
  fun startCompressImage(uri: String, format: String, quality: Long, outputUri: String, taskId: String)
  /**
   * Binary-searches JPEG quality so the output is at or under [targetKb]
   * kilobytes; when quality alone cannot reach the target the image is
   * also downscaled. Throws `invalid_input` for a target below 10 KB.
   */
  fun startCompressToKb(uri: String, targetKb: Long, outputUri: String, taskId: String)
  /** Scales [uri] to [width]x[height] pixels (both >= 1) and saves JPEG. */
  fun startResizeImage(uri: String, width: Long, height: Long, outputUri: String, taskId: String)
  /**
   * Crops the pixel rectangle ([left],[top],[width],[height]) out of
   * [uri] and saves it as JPEG. Throws `invalid_input` when the rectangle
   * leaves the image bounds.
   */
  fun startCropImage(uri: String, left: Long, top: Long, width: Long, height: Long, outputUri: String, taskId: String)
  /** Converts [uri] to [format]: 'jpeg', 'png' or 'webp'. */
  fun startConvertImage(uri: String, format: String, outputUri: String, taskId: String)
  /** Re-encodes [uri] as JPEG so no EXIF/GPS metadata survives. */
  fun startStripExif(uri: String, outputUri: String, taskId: String)
  /**
   * Composes a printable 4×6 inch passport sheet (1200×1800 px, 300 dpi)
   * from [uri]: the photo is centre-cropped to 3:4, scaled to 413×531 px
   * (35×45 mm) and tiled [copies] times (1..6) with light cut guides.
   */
  fun startPassportSheet(uri: String, copies: Long, outputUri: String, taskId: String)
  /**
   * Writes small app-generated PNG bytes (e.g. a drawn signature) to
   * [uri]. Not for bulk file content: callers cap the payload.
   */
  fun writeImageBytes(uri: String, png: ByteArray)
  /** Requests cancellation of a running task. Safe when unknown. */
  fun cancel(taskId: String)

  companion object {
    /** The codec used by ImageToolsApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
    /** Sets up an instance of `ImageToolsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImageToolsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.inspectImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.inspectImage(uriArg))
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startCompressImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val formatArg = args[1] as String
            val qualityArg = args[2] as Long
            val outputUriArg = args[3] as String
            val taskIdArg = args[4] as String
            val wrapped: List<Any?> = try {
              api.startCompressImage(uriArg, formatArg, qualityArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startCompressToKb$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val targetKbArg = args[1] as Long
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startCompressToKb(uriArg, targetKbArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startResizeImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val widthArg = args[1] as Long
            val heightArg = args[2] as Long
            val outputUriArg = args[3] as String
            val taskIdArg = args[4] as String
            val wrapped: List<Any?> = try {
              api.startResizeImage(uriArg, widthArg, heightArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startCropImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val leftArg = args[1] as Long
            val topArg = args[2] as Long
            val widthArg = args[3] as Long
            val heightArg = args[4] as Long
            val outputUriArg = args[5] as String
            val taskIdArg = args[6] as String
            val wrapped: List<Any?> = try {
              api.startCropImage(uriArg, leftArg, topArg, widthArg, heightArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startConvertImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val formatArg = args[1] as String
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startConvertImage(uriArg, formatArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startStripExif$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val outputUriArg = args[1] as String
            val taskIdArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.startStripExif(uriArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.startPassportSheet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val copiesArg = args[1] as Long
            val outputUriArg = args[2] as String
            val taskIdArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.startPassportSheet(uriArg, copiesArg, outputUriArg, taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.writeImageBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val pngArg = args[1] as ByteArray
            val wrapped: List<Any?> = try {
              api.writeImageBytes(uriArg, pngArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.siliph.ImageToolsApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              SiliphBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Flutter results for picker requests.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class FileResultsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FileResultsApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
  }
  fun onOpenResult(filesArg: List<FileMeta>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.FileResultsApi.onOpenResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(filesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPickImagesResult(filesArg: List<FileMeta>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.FileResultsApi.onPickImagesResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(filesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCreateDocumentResult(fileArg: FileMeta?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.FileResultsApi.onCreateDocumentResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(fileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPickFolderResult(treeUriArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.FileResultsApi.onPickFolderResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(treeUriArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Native -> Flutter events for long-running tasks keyed by taskId.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TaskEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TaskEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      SiliphBridgePigeonCodec()
    }
  }
  fun onProgress(taskIdArg: String, fractionArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, fractionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onComplete(taskIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onError(taskIdArg: String, codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Result URIs for tasks that create multiple files (e.g. PDF pages
   * rendered to images). Delivered before [onComplete].
   */
  fun onFilesResult(taskIdArg: String, urisArg: List<String>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onFilesResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, urisArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Duplicate groups for find-duplicates tasks. Delivered before
   * [onComplete].
   */
  fun onDuplicatesResult(taskIdArg: String, groupsArg: List<DuplicateGroup>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onDuplicatesResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, groupsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Storage breakdown for analyzer tasks. Delivered before [onComplete]. */
  fun onStorageResult(taskIdArg: String, entriesArg: List<StorageEntry>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.siliph.TaskEventsApi.onStorageResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, entriesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SiliphBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
